.PHONY: clean All

All:
	@echo "----------Building project:[ LabelWindow - Debug ]----------"
	@cd "/home/tiger/cpp/LabelWindow" && "$(MAKE)" -f  "LabelWindow.mk"
clean:
	@echo "----------Cleaning project:[ LabelWindow - Debug ]----------"
	@cd "/home/tiger/cpp/LabelWindow" && "$(MAKE)" -f  "LabelWindow.mk" clean
