.PHONY: clean All

All:
	@echo "----------Building project:[ 2-memory_layout - Debug ]----------"
	@cd "2-memory_layout" && "$(MAKE)" -f  "2-memory_layout.mk"
clean:
	@echo "----------Cleaning project:[ 2-memory_layout - Debug ]----------"
	@cd "2-memory_layout" && "$(MAKE)" -f  "2-memory_layout.mk" clean
