.PHONY: clean All

All:
	@echo "----------Building project:[ 16-window - Debug ]----------"
	@cd "16-window" && "$(MAKE)" -f  "16-window.mk"
clean:
	@echo "----------Cleaning project:[ 16-window - Debug ]----------"
	@cd "16-window" && "$(MAKE)" -f  "16-window.mk" clean
