.PHONY: clean All

All:
	@echo "----------Building project:[ 18-Message - Debug ]----------"
	@cd "18-Message" && "$(MAKE)" -f  "18-Message.mk"
clean:
	@echo "----------Cleaning project:[ 18-Message - Debug ]----------"
	@cd "18-Message" && "$(MAKE)" -f  "18-Message.mk" clean
