.PHONY: clean All

All:
	@echo "----------Building project:[ 24-Glade - Debug ]----------"
	@cd "24-Glade" && "$(MAKE)" -f  "24-Glade.mk"
clean:
	@echo "----------Cleaning project:[ 24-Glade - Debug ]----------"
	@cd "24-Glade" && "$(MAKE)" -f  "24-Glade.mk" clean
