.PHONY: clean All

All:
	@echo "----------Building project:[ Process - Debug ]----------"
	@cd "Process" && "$(MAKE)" -f  "Process.mk"
clean:
	@echo "----------Cleaning project:[ Process - Debug ]----------"
	@cd "Process" && "$(MAKE)" -f  "Process.mk" clean
